# Access using : http://localhost:8123 with test:test
services:
  homeassistant:
    container_name: homeassistant-yokis
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./custom_components/yokis:/config/custom_components/yokis
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    network_mode: host